const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

// React Native 0.81 vendors {fmt} 11.0.2, whose compile-time format-string
// checking uses `consteval` in a way Xcode 26's stricter Clang rejects
// ("call to consteval function … is not a constant expression"). Fixed upstream
// in fmt 12, but only pulled into RN >= 0.83.9 — NOT back-ported to 0.81.
//
// Scoped workaround: build ONLY the fmt pod as C++17. `consteval` didn't exist
// pre-C++20, so fmt skips the compile-time path and falls back to runtime
// format-string validation. Everything else keeps its C++20 setting.
//
// ios/ is regenerated by `expo prebuild`, so this runs as a config plugin to
// re-apply on every prebuild. Remove once RN bumps fmt (>= 0.83.9 / 0.85.x).
const SNIPPET = `
    installer.pods_project.targets.each do |target|
      if target.name == 'fmt'
        target.build_configurations.each do |bc|
          bc.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end
`;

module.exports = function withFmtConstevalFix(config) {
  return withDangerousMod(config, [
    "ios",
    (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, "Podfile");
      let contents = fs.readFileSync(podfile, "utf8");
      if (!contents.includes("target.name == 'fmt'")) {
        // Insert AFTER react_native_post_install(...) so this wins if it also
        // touches build settings. Matches the multi-line call up to its closing `)`.
        contents = contents.replace(
          /(react_native_post_install\([\s\S]*?\n\s*\)\n)/,
          `$1${SNIPPET}`,
        );
        fs.writeFileSync(podfile, contents);
      }
      return cfg;
    },
  ]);
};
